// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ex.domain;

import com.ex.domain.RestaurantDataOnDemand;
import com.ex.domain.RestaurantIntegrationTest;
import com.ex.repository.RestaurantRepository;
import com.ex.service.RestaurantService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RestaurantIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RestaurantIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RestaurantIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RestaurantIntegrationTest: @Transactional;
    
    @Autowired
    private RestaurantDataOnDemand RestaurantIntegrationTest.dod;
    
    @Autowired
    RestaurantService RestaurantIntegrationTest.restaurantService;
    
    @Autowired
    RestaurantRepository RestaurantIntegrationTest.restaurantRepository;
    
    @Test
    public void RestaurantIntegrationTest.testCountAllRestaurants() {
        Assert.assertNotNull("Data on demand for 'Restaurant' failed to initialize correctly", dod.getRandomRestaurant());
        long count = restaurantService.countAllRestaurants();
        Assert.assertTrue("Counter for 'Restaurant' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RestaurantIntegrationTest.testFindRestaurant() {
        Restaurant obj = dod.getRandomRestaurant();
        Assert.assertNotNull("Data on demand for 'Restaurant' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Restaurant' failed to provide an identifier", id);
        obj = restaurantService.findRestaurant(id);
        Assert.assertNotNull("Find method for 'Restaurant' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Restaurant' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RestaurantIntegrationTest.testFindAllRestaurants() {
        Assert.assertNotNull("Data on demand for 'Restaurant' failed to initialize correctly", dod.getRandomRestaurant());
        long count = restaurantService.countAllRestaurants();
        Assert.assertTrue("Too expensive to perform a find all test for 'Restaurant', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Restaurant> result = restaurantService.findAllRestaurants();
        Assert.assertNotNull("Find all method for 'Restaurant' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Restaurant' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RestaurantIntegrationTest.testFindRestaurantEntries() {
        Assert.assertNotNull("Data on demand for 'Restaurant' failed to initialize correctly", dod.getRandomRestaurant());
        long count = restaurantService.countAllRestaurants();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Restaurant> result = restaurantService.findRestaurantEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Restaurant' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Restaurant' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RestaurantIntegrationTest.testFlush() {
        Restaurant obj = dod.getRandomRestaurant();
        Assert.assertNotNull("Data on demand for 'Restaurant' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Restaurant' failed to provide an identifier", id);
        obj = restaurantService.findRestaurant(id);
        Assert.assertNotNull("Find method for 'Restaurant' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRestaurant(obj);
        Integer currentVersion = obj.getVersion();
        restaurantRepository.flush();
        Assert.assertTrue("Version for 'Restaurant' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RestaurantIntegrationTest.testUpdateRestaurantUpdate() {
        Restaurant obj = dod.getRandomRestaurant();
        Assert.assertNotNull("Data on demand for 'Restaurant' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Restaurant' failed to provide an identifier", id);
        obj = restaurantService.findRestaurant(id);
        boolean modified =  dod.modifyRestaurant(obj);
        Integer currentVersion = obj.getVersion();
        Restaurant merged = restaurantService.updateRestaurant(obj);
        restaurantRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Restaurant' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RestaurantIntegrationTest.testSaveRestaurant() {
        Assert.assertNotNull("Data on demand for 'Restaurant' failed to initialize correctly", dod.getRandomRestaurant());
        Restaurant obj = dod.getNewTransientRestaurant(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Restaurant' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Restaurant' identifier to be null", obj.getId());
        restaurantService.saveRestaurant(obj);
        restaurantRepository.flush();
        Assert.assertNotNull("Expected 'Restaurant' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RestaurantIntegrationTest.testDeleteRestaurant() {
        Restaurant obj = dod.getRandomRestaurant();
        Assert.assertNotNull("Data on demand for 'Restaurant' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Restaurant' failed to provide an identifier", id);
        obj = restaurantService.findRestaurant(id);
        restaurantService.deleteRestaurant(obj);
        restaurantRepository.flush();
        Assert.assertNull("Failed to remove 'Restaurant' with identifier '" + id + "'", restaurantService.findRestaurant(id));
    }
    
}
