// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ex.domain;

import com.ex.domain.Restaurant;
import com.ex.domain.RestaurantDataOnDemand;
import com.ex.repository.RestaurantRepository;
import com.ex.service.RestaurantService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect RestaurantDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RestaurantDataOnDemand: @Component;
    
    private Random RestaurantDataOnDemand.rnd = new SecureRandom();
    
    private List<Restaurant> RestaurantDataOnDemand.data;
    
    @Autowired
    RestaurantService RestaurantDataOnDemand.restaurantService;
    
    @Autowired
    RestaurantRepository RestaurantDataOnDemand.restaurantRepository;
    
    public Restaurant RestaurantDataOnDemand.getNewTransientRestaurant(int index) {
        Restaurant obj = new Restaurant();
        setName(obj, index);
        setWkt(obj, index);
        return obj;
    }
    
    public void RestaurantDataOnDemand.setName(Restaurant obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void RestaurantDataOnDemand.setWkt(Restaurant obj, int index) {
        String wkt = "wkt_" + index;
        obj.setWkt(wkt);
    }
    
    public Restaurant RestaurantDataOnDemand.getSpecificRestaurant(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Restaurant obj = data.get(index);
        Long id = obj.getId();
        return restaurantService.findRestaurant(id);
    }
    
    public Restaurant RestaurantDataOnDemand.getRandomRestaurant() {
        init();
        Restaurant obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return restaurantService.findRestaurant(id);
    }
    
    public boolean RestaurantDataOnDemand.modifyRestaurant(Restaurant obj) {
        return false;
    }
    
    public void RestaurantDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = restaurantService.findRestaurantEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Restaurant' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Restaurant>();
        for (int i = 0; i < 10; i++) {
            Restaurant obj = getNewTransientRestaurant(i);
            try {
                restaurantService.saveRestaurant(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            restaurantRepository.flush();
            data.add(obj);
        }
    }
    
}
