// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ex.domain;

import com.ex.domain.RestaurantDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect RestaurantDataOnDemand_Roo_Configurable {
    
    declare @type: RestaurantDataOnDemand: @Configurable;
    
}
